### get all pets
GET http://localhost:3000/pets

### get a pet
GET http://localhost:3000/pets/6

###
GET http://localhost:3000/pets/0

###
GET http://localhost:3000/pets/5

###
GET http://localhost:3000/

###
GET http://localhost:3000/boom

###
GET http://localhost:3000/blah

###
GET http://localhost:3000/pets/-1

### creates a new pet
POST http://localhost:3000/pets
Content-Type: application/json

{
    "kind": "cat",
    "name": "Bruce",
    "age": 3
}

### patch a pet
PATCH http://localhost:3000/pets/1
Content-Type: application/json

{
    
    "name": "Job"
    
}

### delete a pet
DELETE http://localhost:3000/pets/19

### put a pet
PUT http://localhost:3000/pets/6
Content-Type: application/json

{
    "name": "tom",
    "kind": "cat",
    "age": 2
}